sudo: false

services:
  - docker

before_script:
  - docker-compose -v
  - docker-compose build sshproxy app
  - docker-compose run --rm app php ./tests/Keboola/loadS3.php
  - docker-compose run --rm app vendor/bin/phpunit
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository keboola keboola.ex-db-redshift-cursors`
  - docker tag keboola/ex-db-redshift:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login keboola keboola.ex-db-redshift-cursors)
  - docker push $REPOSITORY:master
  - docker pull quay.io/keboola/syrup-cli:latest

script:


deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true


